package com.mrb.action;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mrb.bs.BookBS;

/**
 * MyEclipse Struts Creation date: 02-25-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * 
 * 根据Type浏览Book的Action
 * 
 */
public class BookTypeAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * 
	 * 根据类型编码返回book列表
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request, HttpServletResponse response) {

		BookBS bs = new BookBS();

		String typeCode = request.getParameter("code");

		ArrayList bookByTypeList = bs.getBookByTypeList(typeCode);

		request.setAttribute("bookList", bookByTypeList);
		request.setAttribute("typeCode", typeCode);

		// System.out.println("typeCode:"+typeCode);

		return mapping.findForward("show");
	}
}