package com.mrb.action;

/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
import java.util.ArrayList;
import java.util.HashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.mrb.bean.TypeSumBean;
import com.mrb.bs.BookTypeBS;
import com.mrb.bs.TypeSumBS;
import com.mrb.tool.lucene.Index;

/**
 * MyEclipse Struts Creation date: 02-25-2011
 * 
 * XDoclet definition:
 * 
 * @struts.action validate="true"
 * 
 * 请求首页信息的Action
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		return mapping.findForward("index");
	}
}